STAS:
  dataset_type: '1617_modalsEC'
  dataset_util: 'util_dataset'
  preTrain_MSM: 'pre_training/MSM'
  preTrain_MTM: 'pre_training/MTM'  
  multiScale_step: 2
  multiLength_step: 1
  set_ord_max_prepValue: 35 
  set_ord_prep_space: 0.5
  set_min_CtemValue: -5 
  set_max_CtemValue: 40 
  set_Ctem_space: 3
  set_min_CpressValue: 1000
  set_max_CpressValue: 1028 
  set_Cpress_space: 1
  set_max_CwindVoc: 400
  set_max_CwindDre: 20
  set_CwVoc_space: 5
  set_CwDre_space: 1
  set_min_CdewValue: -5 
  set_max_CdewValue: 40
  set_Cdew_space: 3
  set_max_CrainValue: 90 
  set_Crain_space: 3 
  startDate: '201608'
  endDate: '201608'
  uniform_ecSize: 18
  uniform_upDownFeaSize: 18
  uniform_t1sLen: 5 
  in_channel: 57
  ed_out_channel: 64
  ts_out_channel: 64
  ts_seq: 6
  alpha: 0.0002
  beta: 1
  init_lr: 0.0001
  lr_decay: 0.5
  lr_decay_epoch: 10
  lr_decay_iter: 2000
  init_best_error: 1000
  weight_decay: 0
  training_inv: 2 
  train_batch_size: 64
  test_batch_size: 64
  resample_range: 64
  split: 4
  noiseStd: 0.001
  max_epoch: 100000000
  preset_iter: 100
  max_iter: 500
  save_iter: 100
  pre_train_batch_size: 64
  pre_test_batch_size: 32
  
SAS:
  dataset_type: '1617_modalsEC'
  dataset_util: 'util_dataset'
  preTrain_MSM: 'pre_training/MSM'
  multiScale_step: 2
  set_max_prepValue: 35 
  set_prep_space: 0.5  
  startDate: '201609'
  endDate: '201609'
  uniform_ecSize: 18
  uniform_upDownFeaSize: 18
  uniform_t1sLen: 5
  in_channel: 57
  ed_out_channel: 64
  ts_out_channel: 64
  ts_seq: 6
  alpha: 0.0002
  beta: 1
  init_lr: 0.0001
  lr_decay: 0.5
  lr_decay_epoch: 10
  lr_decay_iter: 2000
  init_best_error: 1000
  weight_decay: 0
  training_inv: 2 
  train_batch_size: 128
  test_batch_size: 64
  resample_range: 64
  split: 4
  noiseStd: 0.001
  max_epoch: 8000
  preset_iter: 100
  max_iter: 500
  save_iter: 100
  
TAS:
  dataset_type: '1617_modalsEC'
  dataset_util: 'util_dataset'
  preTrain_MTM: 'pre_training/MTM'  
  multiLength_step: 1
  set_ord_max_prepValue: 35 
  set_ord_prep_space: 0.5
  set_min_CtemValue: -5 
  set_max_CtemValue: 40 
  set_Ctem_space: 3
  set_min_CpressValue: 1000
  set_max_CpressValue: 1028 
  set_Cpress_space: 1
  set_max_CwindVoc: 400
  set_max_CwindDre: 20
  set_CwVoc_space: 5
  set_CwDre_space: 1
  set_min_CdewValue: -5 
  set_max_CdewValue: 40
  set_Cdew_space: 3
  set_max_CrainValue: 90 
  set_Crain_space: 3 
  startDate: '201609'
  endDate: '201609'
  in_channel: 57
  origin_ecSize: 29
  uniform_t1sLen: 5
  uniform_upDownFeaSize: 18   
  ed_out_channel: 64 
  ts_out_channel: 64
  ts_seq: 6
  alpha: 0.0002
  beta: 1
  init_lr: 0.0001
  lr_decay: 0.5
  lr_decay_epoch: 10
  lr_decay_iter: 2000
  init_best_error: 1000
  weight_decay: 0
  training_inv: 2 
  train_batch_size: 128
  test_batch_size: 64
  resample_range: 64
  split: 4
  noiseStd: 0.001
  max_epoch: 1000
  preset_iter: 100
  max_iter: 500
  save_iter: 100
  
OBA:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  set_max_prepValue: 35 
  set_prep_space: 0.5  
  startDate: '201609'
  endDate: '201609'
  alpha: 0.0002
  beta: 1
  init_lr: 0.0001
  lr_decay: 0.5
  lr_decay_epoch: 10
  lr_decay_iter: 2000
  init_best_error: 1000
  weight_decay: 0
  training_inv: 2 
  train_batch_size: 64
  test_batch_size: 64
  resample_range: 64
  split: 4
  noiseStd: 0.001
  max_epoch: 600
  preset_iter: 100
  max_iter: 500
  save_iter: 100
  
  
FPN:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608'
  split_ratio: 0.8
  EC_size: 29
  crop_scale: 1
  in_feature: 57
  hidden_feature: 64
  train_batch_size: 256
  test_batch_size: 64
  training_inv: 2
  learning_rate: 0.0001
  weight_decay: 0
  max_epoch: 1000
  benchmark_name: FPN
  
FCN:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608'
  split_ratio: 0.8
  EC_size: 29
  ts_seq: 6
  crop_scale: 1
  in_feature: 57
  hidden_feature: 256
  hidden_iter_feature: 64
  train_batch_size: 256
  test_batch_size: 64
  training_inv: 2
  learning_rate: 0.0001
  weight_decay: 0
  max_epoch: 1000
  benchmark_name: FCN
  
LSTM:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608'
  split_ratio: 0.8
  EC_size: 29
  crop_scale: 1  
  in_feature_size_lstm: 57
  hidden_feature_size_lstm: 256
  in_feature_size_convLstm: 57
  hidden_feature_size_convLstm: 256
  ts_seq: 6
  train_batch_size: 256
  test_batch_size: 64
  training_inv: 2
  learning_rate_lstm: 0.0001
  learning_rate_convLstm: 0.0001
  weight_decay: 0
  max_epoch: 1000
  benchmark_name1: LSTM
  benchmark_name2: convLSTM
 
MLP:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608'
  split_ratio: 0.8
  EC_size: 29
  crop_scale: 1
  hidden_layer_sizes: (128,)
  activation: relu
  solver: adam
  alpha: 0.0001
  batch_size: auto
  learning_rate: constant
  learning_rate_init: 0.001
  shuffle: True
  max_iter: 5000
  warm_start: False
  early_stopping: False
  benchmark_name: MutiProp
  repetitions: 30
  
SVR:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608'
  split_ratio: 0.8
  EC_size: 29
  crop_scale: 1
  Penalty: 1
  epsilon: 0.01
  kernel: rbf
  degree: 3
  gamma: auto
  shrinking: True
  tol: 0.001
  max_iter: 5000
  benchmark_name: SVReg
  repetitions: 30
  
LR:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608'
  split_ratio: 0.8
  ts_seq: 6
  in_channel: 57
  EC_size: 29
  crop_scale: 1
  fit_intercept: False
  normalize: False
  copy_X: True
  n_jobs: 8
  benchmark_name: LinearReg
  LR_repetitions: 30
  LR_iter_repetitions: 10
  
RF:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608'
  split_ratio: 0.8
  ts_seq: 6
  in_channel: 57
  EC_size: 29
  crop_scale: 1
  #
  n_estimators: 10
  criterion: mae
  max_features: auto
  max_depth: None
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0
  max_leaf_nodes: None
  bootstrap: True
  n_jobs: 16
  random_state: None
  verbose: 0
  warm_start: False
  benchmark_name: RandomForest
  repetitions: 10
  
Bayes:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608'
  split_ratio: 0.8
  ts_seq: 6
  in_channel: 57
  EC_size: 29
  crop_scale: 1
  rain_cls_interval: 5 
  alpha: 1
  fit_prior: True
  class_prior: None
  benchmark_name: Bayesian
  repetitions: 30
  
IFS:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608'
  split_ratio: 0.8
  EC_size: 29
  crop_scale: 1
  copy_X: True
  n_jobs: 3
  benchmark_name: ECOrigin
  repetitions: 30
  
public_var:
  dataset_type: '1617_benchmarkEC'
  dataset_util: 'util_dataset'
  startDate: '201608'
  endDate: '201608' 
